# Generated by Django 4.0.3 on 2022-03-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdate',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventtime',
            name='event_date',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventDate',
        ),
        migrations.DeleteModel(
            name='EventTime',
        ),
    ]
