# Generated by Django 4.0.3 on 2022-03-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventapp', '0002_remove_eventdate_event_remove_eventtime_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('event_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.eventdate')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('post_code', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.eventdate')),
            ],
        ),
    ]
