# Generated by Django 4.0.3 on 2022-03-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_rename_event_date_eventtime_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtime',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.event'),
        ),
        migrations.AlterField(
            model_name='eventtime',
            name='time',
            field=models.TimeField(unique=True),
        ),
    ]
